### ISSUE TITLE
3V3 in HV mode?

### ISSUE THREAD

**Issue by nerdralph** [wagiminator/ATtiny84-TinyCalibrator#2]
Does HV work with the target Vcc at 3V3?  For HV programming mode, the datasheet says: "Apply 4.5 - 5.5V between V CC and GND".

**Comment by wagiminator** [comment]
I know, but it still works with no problems.

**Comment by nerdralph** [comment]
OK, I hadn't tested it myself, but I'm not surprised it works outside the datasheet specs.

**Comment by wagiminator** [comment]
One picture in the data sheet shows 1.8V-5.5V, so I just tried it out before implementing extra low-voltage serial programming routines.
