### ISSUE TITLE
keep one version of code

### ISSUE THREAD

**Issue by nerdralph** [wagiminator/ATtiny84-TinyCalibrator#4]
I noticed you have a .ino file for Arduino builds, and a .c file for building with a makefile.  If you have just the .ino file, you can compile it with a makefile by passing the -x option to avr-gcc.
https://github.com/nerdralph/picoUART/blob/master/examples/make.inc#L8

**Comment by wagiminator** [comment]
That's handy, I'll try it out. Thank you!

**Comment by wagiminator** [comment]
It works! Thanks again for the great tip. Do you know why the required flash memory size differs slightly from the other method (sometimes a few bytes more, sometimes a few bytes less)?

**Comment by nerdralph** [comment]
> 
> 
> It works! Thanks again for the great tip. Do you know why the required flash memory size differs slightly from the other method (sometimes a few bytes more, sometimes a few bytes less)?

I'm going to guess you're using a different version of avr-gcc from the shell vs the Arduino IDE.

**Comment by wagiminator** [comment]
That makes sense. If I find the time, maybe I'll disassemble it and try to find the differences.
