### ISSUE TITLE
was SCI delay needed?

### ISSUE THREAD

**Issue by nerdralph** [wagiminator/ATtiny84-TinyCalibrator#5]
https://github.com/wagiminator/ATtiny84-TinyCalibrator/blob/main/software/TinyCalibrator_v0.5.ino#L327

The datasheet says the minimum clock period is 220ns.  I had no problems with a period of 250ns (cbi + sbi instructions on a 16MHz AVR), so I'd think that you certainly wouldn't need the delay on a t84 running at 12MHz.

**Comment by wagiminator** [comment]
Oh yes, you are right. I forgot that cbi and sbi each need two clock cycles ;-) I'll change that in the next version.
